apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "deploy.fullname" . }}
data:
  AMQP_URI: "{{ .Values.secret.amqpURI | b64enc }}"
  RABBITMQ_HOST: "{{ .Values.secret.rabbitmqHost | b64enc }}"
  RABBITMQ_USER: "{{ .Values.secret.rabbitmqUser | b64enc }}"
  RABBITMQ_PASSWORD: "{{ .Values.secret.rabbitmqPassword | b64enc }}"
  QUEUE_NAME: "{{ .Values.secret.queueName | b64enc }}"
  EXCHANGE_NAME: "{{ .Values.secret.exchangeName | b64enc }}"
  
